apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hokienest-ingress
  namespace: hnest-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - hokienest.discovery.cs.vt.edu
    secretName: hokienest-tls
  rules:
  - host: hokienest.discovery.cs.vt.edu
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hokienest-backend
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hokienest-frontend
            port:
              number: 80